def string_attr(the_object, the_attribute):
    prop = getattr(the_object, the_attribute, None)
    if prop:
        try:
            return str(prop)
        except:
            return None
    else:
        return None



class EventCatalog(object):

    #GROUPS
    GROUP_CREATE = "GROUP_CREATE"

    #CUSTOMER
    CUSTOMER_CREATE = "CUSTOMER_CREATE"
    CUSTOMER_APPLY_COUPON = "CUSTOMER_APPLY_COUPON"
    CUSTOMER_REMOVE_COUPON = "CUSTOMER_REMOVE_COUPON"
    CUSTOMER_ADD_PLAN = "CUSTOMER_ADD_PLAN"
    CUSTOMER_CANCEL_PLAN = "CUSTOMER_CANCEL_PLAN"
    CUSTOMER_ADD_PAYOUT = "CUSTOMER_ADD_PAYOUT"
    CUSTOMER_CANCEL_PAYOUT = "CUSTOMER_CANCEL_PAYOUT"
    CUSTOMER_CHARGE_ATTEMPT = "CUSTOMER_CHARGE_ATTEMPT"
    CUSTOMER_CLEAR_DEBT = "CUSTOMER_CLEAR_DEBT"

    #COUPONS
    COUPON_CREATE = "COUPON_CREATE"
    COUPON_UPDATE = "COUPON_UPDATE"
    COUPON_DELETE = "COUPON_DELETE"
    COUPON_EXPIRE = "COUPON_EXPIRE"

    #Plan Invoice
    PI_PRORATE_LAST = "PI_PRORATE_LAST"
    PI_CREATE = "PI_CREATE"
    PI_ROLLOVER = "PI_ROLLOVER"

    #Payout Invoice:
    POI_CREATE = "POI_CREATE"
    POI_ROLLOVER = "POI_ROLLOVER"
    POI_MAKE_PAYOUT = "POI_MAKE_PAYOUT"
    POI_PAYOUT_ATTEMPT = "POI_PAYOUT_ATTEMPT"

    #Plans
    PLAN_CREATE = "PLAN_CREATE"
    PLAN_UPDATE = "PLAN_UPDATE"
    PLAN_DELETE = "PLAN_DELETE"


    #Payout
    PAYOUT_CREATE = "PAYOUT_CREATE"
    PAYOUT_UPDATE = "PAYOUT_UPDATE"
    PAYOUT_DELETE = "PAYOUT_DELETE"





